server:
  port: 8001
spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
redisson:
  # 单机模式配置
  singleServerConfig:
    address: "redis://${spring.data.redis.host}:${spring.data.redis.port}"
    timeout: 10000                # 命令执行最大超时，默认3000ms
    connectTimeout: 10000         # TCP建立连接的超时，默认10000ms
    idleConnectionTimeout: 10000  # 空闲连接超时，默认10000ms
    pingConnectionInterval: 30000 # 每隔30秒PING一次，避免长时间空闲被回收
    connectionPoolSize: 64
    connectionMinimumIdleSize: 10
short-link:
  domain:
    default: http://nurl.ink:8001
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
