server:
  port: 8001
  tomcat:
    connection-timeout: 20000 # 连接超时时间（毫秒）
    threads:
      max: 200 # 最大工作线程数
    accept-count: 100 # 等待队列长度
    max-http-form-post-size: 65536 # 请求头最大限制（字节）
spring:
  application:
    name: shortlink-project
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: short-link_project-service_stats-save_pg
    topic: short-link_project-service_topic
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg

redisson:
  # 单机模式配置
  singleServerConfig:
    address: "redis://${spring.data.redis.host}:${spring.data.redis.port}"
    timeout: 10000                # 命令执行最大超时，默认3000ms
    connectTimeout: 10000         # TCP建立连接的超时，默认10000ms
    idleConnectionTimeout: 10000  # 空闲连接超时，默认10000ms
    pingConnectionInterval: 30000 # 每隔30秒PING一次，避免长时间空闲被回收
    connectionPoolSize: 64
    connectionMinimumIdleSize: 10
short-link:
  domain:
    default: http://nurl.ink:8001
shortlink:
  snowflake:
    datacenter-id: 1
    worker-id:     1
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园,github'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - github.com
        - xiaolincoding.com
        - localhost
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
